# Generated by Django 5.2.13 on 2026-05-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
