# Generated by Django 5.2.13 on 2026-05-10 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='User',
        ),
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='Custumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.custumer'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
