# Generated by Django 5.2.13 on 2026-05-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_address_user_custumer_address_custumer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custumer',
            old_name='utilizador',
            new_name='user',
        ),
    ]
