# Generated by Django 5.2.13 on 2026-05-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_utilizador_custumer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custumer',
            options={},
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='UserId',
        ),
        migrations.AddField(
            model_name='custumer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custumer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
