# Generated by Django 5.2.13 on 2026-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_custumer_options_remove_custumer_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Custumer',
        ),
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='Custumer',
        ),
    ]
