# Generated by Django 5.2.13 on 2026-05-10 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_address_custumer_alter_address_country_and_more'),
        ('userauth', '0004_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='userauth.profile'),
        ),
    ]
