# Generated by Django 5.2.13 on 2026-05-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_address_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='profile',
            new_name='Custumer',
        ),
    ]
