# Generated by Django 5.2.13 on 2026-05-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
