# Generated by Django 5.2.13 on 2026-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
