# Generated by Django 5.2.13 on 2026-05-10 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_profile_address_custumer'),
        ('userauth', '0004_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Custumer',
        ),
    ]
