# Generated by Django 5.2.13 on 2026-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_rename_profile_custumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
