# Generated by Django 5.2.14 on 2026-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_custumer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
